import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy - LibertyPrinterFix",
  description: "Read the comprehensive Privacy Policy for LibertyPrinterFix, detailing how we collect, use, and safeguard your data.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="container" style={{ maxWidth: '800px', padding: '4rem 1rem' }}>
      <div className="article-content">
        <h1>Privacy Policy for Liberty Printer Fix</h1>
        <p><strong>Last Updated: July 19, 2026</strong></p>
        
        <p>Welcome to Liberty Printer Fix ("we," "us," "our," or the "Company"), accessible at <a href="https://libertyprinterfix.com">https://libertyprinterfix.com</a> (the "Website" or "Service"). We are a business operating in the State of Florida, United States.</p>
        
        <p>This Privacy Policy describes how we collect, use, disclose, and safeguard your information when you visit our Website, make a purchase, subscribe to our communications, or otherwise interact with us. Please read this Privacy Policy carefully. By accessing or using the Website, you agree to the collection and use of information in accordance with this Privacy Policy. If you do not agree with the terms of this Privacy Policy, please do not access the Website.</p>
        
        <p>We reserve the right to make changes to this Privacy Policy at any time and for any reason. We will alert you about any changes by updating the "Last Updated" date of this Privacy Policy. You are encouraged to periodically review this Privacy Policy to stay informed of updates.</p>

        <h2>1. Definitions</h2>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li><strong>"Personal Data"</strong> (or "Personal Information") means any information that identifies, relates to, describes, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular individual or household.</li>
          <li><strong>"Usage Data"</strong> means data collected automatically, generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>"Cookies"</strong> are small files placed on your device (computer, mobile device, or tablet) by a website, containing details of your browsing history on that website among its many uses.</li>
          <li><strong>"Data Controller"</strong> means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any Personal Data are, or are to be, processed. For the purposes of this Privacy Policy, we are the Data Controller of your Personal Data.</li>
          <li><strong>"Data Processor"</strong> (or "Service Provider") means any natural or legal person who processes data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
          <li><strong>"Data Subject"</strong> (or "User" / "You") means any living individual who is using our Service and is the subject of Personal Data.</li>
        </ul>

        <h2>2. Information We Collect</h2>
        <h3>2.1 Personal Data You Provide to Us</h3>
        <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include, but is not limited to:</p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li><strong>Social media profile information</strong> (for example, when you connect or sign in using Facebook, Twitter/X, Google, or other social media accounts, we may receive profile information such as your name, email address, profile picture, and public profile details, in accordance with the authorization procedures and privacy settings of those platforms)</li>
          <li><strong>Payment information</strong> (when you purchase products or services from us; see Section 6 below)</li>
          <li><strong>Any other information you voluntarily provide</strong> through contact forms, support tickets, comments, surveys, or other interactive features of the Website</li>
        </ul>

        <h3>2.2 Usage Data (Collected Automatically)</h3>
        <p>We may also collect information that your browser sends whenever you visit our Website. This Usage Data may include:</p>
        <ul>
          <li>Your device's Internet Protocol (IP) address</li>
          <li>Browser type and browser version</li>
          <li>The pages of our Website that you visit</li>
          <li>The time and date of your visit</li>
          <li>The time spent on those pages</li>
          <li>Unique device identifiers</li>
          <li>Referring/exit pages and URLs</li>
          <li>Operating system and platform</li>
          <li>Other diagnostic data</li>
        </ul>
        <p>When you access the Website via a mobile device, we may collect certain information automatically, including the type of mobile device you use, your mobile device's unique ID, the IP address of your mobile device, your mobile operating system, and the type of mobile browser you use.</p>

        <h3>2.3 Information from Children Under 13</h3>
        <p>We may collect information from children under the age of 13. We do so only in compliance with the Children's Online Privacy Protection Act (COPPA). Please see Section 12 (Children's Privacy) for detailed information about our practices, the parental consent we obtain, and the rights of parents and guardians.</p>

        <h2>3. Tracking Technologies and Cookies</h2>
        <p>We use Cookies and similar tracking technologies (such as web beacons, pixels, tags, and scripts) to track activity on our Service and store certain information.</p>
        
        <h3>3.1 Types of Cookies We Use</h3>
        <ul>
          <li><strong>Necessary / Essential Cookies</strong> (Session Cookies): These Cookies are essential to provide you with services available through the Website and to enable you to use some of its features. Without these Cookies, the services you have asked for cannot be provided.</li>
          <li><strong>Functionality Cookies</strong> (Persistent Cookies): These Cookies allow us to remember choices you make when you use the Website, such as remembering your login details or language preference.</li>
          <li><strong>Analytics and Performance Cookies:</strong> These Cookies collect information about how visitors use the Website, which pages are visited most often, and whether visitors receive error messages. See Section 4 below.</li>
          <li><strong>Advertising and Targeting Cookies:</strong> These Cookies are used to deliver advertisements relevant to you and your interests, and to measure the effectiveness of advertising campaigns. See Sections 5 and 7 below.</li>
        </ul>

        <h3>3.2 Your Cookie Choices</h3>
        <p>You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some portions of our Service. Most web browsers allow you to manage your Cookie preferences through the browser settings menu.</p>

        <h2>4. Analytics</h2>
        <p>We use third-party analytics tools, including <strong>Google Analytics</strong>, to monitor and analyze the use of our Service.</p>
        <p>Google Analytics is a web analytics service offered by Google LLC ("Google") that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
        <p>You can opt out of having your activity on the Service made available to Google Analytics by installing the Google Analytics opt-out browser add-on, available at: <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">https://tools.google.com/dlpage/gaoptout</a>. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visit activity.</p>
        <p>For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a></p>

        <h3>4.1 Mouseflow</h3>
        <p>We use <strong>Mouseflow</strong>, a session replay and heatmap analytics service provided by Mouseflow ApS. Mouseflow may record mouse clicks, mouse movements, scrolling activity, and keystroke information that you voluntarily enter on our Website (excluding fields designated as sensitive). Mouseflow helps us understand how visitors interact with our Website so we can improve usability and the user experience.</p>
        <p>Mouseflow does not use this data to identify you personally, and sensitive input fields are excluded from recording by default. You can opt out of Mouseflow recordings at any time by visiting: <a href="https://mouseflow.com/opt-out" target="_blank" rel="noopener noreferrer">https://mouseflow.com/opt-out</a>. For more information, see Mouseflow's Privacy Policy at: <a href="https://mouseflow.com/privacy/" target="_blank" rel="noopener noreferrer">https://mouseflow.com/privacy/</a></p>

        <h2>5. Advertising</h2>
        <p>We may display advertisements on our Website, which may be served by third-party advertising partners (such as Google AdSense or other advertising networks). These third-party vendors use Cookies, web beacons, and similar technologies to serve ads based on your prior visits to our Website and/or other websites on the Internet.</p>
        <ul>
          <li>Google, as a third-party vendor, uses Cookies (including the DART cookie) to serve ads on our Service based on your visit to our Service and other sites on the Internet.</li>
          <li>You may opt out of the use of the DART cookie and personalized advertising by visiting the Google Ads Settings page: <a href="https://adssettings.google.com" target="_blank" rel="noopener noreferrer">https://adssettings.google.com</a></li>
          <li>You can also opt out of some third-party vendors' use of Cookies for personalized advertising by visiting <a href="http://www.aboutads.info/choices" target="_blank" rel="noopener noreferrer">www.aboutads.info/choices</a> (Digital Advertising Alliance) or <a href="http://www.networkadvertising.org/choices" target="_blank" rel="noopener noreferrer">www.networkadvertising.org/choices</a> (Network Advertising Initiative).</li>
        </ul>
        <p>We do not control the Cookies used by third-party advertisers. We encourage you to review the privacy policies of these advertising partners for more information about their practices and how to opt out.</p>

        <h2>6. Payments</h2>
        <p>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g., payment processors such as Stripe, PayPal, or similar providers).</p>
        <p>We will not store or collect your full payment card details on our own servers. That information is provided directly to our third-party payment processors, whose use of your Personal Information is governed by their own privacy policies. These payment processors adhere to the standards set by PCI-DSS (Payment Card Industry Data Security Standard) as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express, and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
        <p>Examples of payment processor privacy policies:</p>
        <ul>
          <li><strong>Stripe:</strong> <a href="https://stripe.com/us/privacy" target="_blank" rel="noopener noreferrer">https://stripe.com/us/privacy</a></li>
          <li><strong>PayPal:</strong> <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full" target="_blank" rel="noopener noreferrer">https://www.paypal.com/webapps/mpp/ua/privacy-full</a></li>
        </ul>
        <p>We may retain limited transaction information (such as the date, amount, and items purchased) for accounting, tax, fraud-prevention, and customer-service purposes.</p>

        <h2>7. Remarketing and Behavioral Advertising</h2>
        <p>We use remarketing services to advertise to you on third-party websites after you have visited our Service. We and our third-party vendors use Cookies to inform, optimize, and serve ads based on your past visits to our Service. Remarketing providers we may use include:</p>
        
        <h3>7.1 Google Ads (AdWords) Remarketing</h3>
        <p>Google Ads remarketing is provided by Google LLC. You can opt out of Google Analytics for Display Advertising and customize Google Display Network ads by visiting the Google Ads Settings page: <a href="https://adssettings.google.com" target="_blank" rel="noopener noreferrer">https://adssettings.google.com</a>. Google also recommends installing the Google Analytics Opt-out Browser Add-on: <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">https://tools.google.com/dlpage/gaoptout</a>. For more information, visit: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a></p>
        
        <h3>7.2 Meta (Facebook) Remarketing</h3>
        <p>Facebook remarketing is provided by Meta Platforms, Inc. You can learn more about interest-based advertising from Facebook by visiting: <a href="https://www.facebook.com/help/516147308587266" target="_blank" rel="noopener noreferrer">https://www.facebook.com/help/516147308587266</a>. To opt out of Facebook's interest-based ads, follow these instructions: <a href="https://www.facebook.com/help/568137493302217" target="_blank" rel="noopener noreferrer">https://www.facebook.com/help/568137493302217</a>. Facebook adheres to the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital Advertising Alliance. For more information, visit Meta's Privacy Policy: <a href="https://www.facebook.com/privacy/policy" target="_blank" rel="noopener noreferrer">https://www.facebook.com/privacy/policy</a></p>

        <h3>7.3 Other Remarketing Networks</h3>
        <p>We may also use remarketing services from Microsoft Advertising, Twitter/X, Pinterest, or similar networks. Each of these providers offers its own opt-out mechanisms, accessible via their respective privacy policies.</p>

        <h2>8. Third-Party Service Providers</h2>
        <p>We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

        <h3>8.1 Invisible reCAPTCHA</h3>
        <p>We use the <strong>Invisible reCAPTCHA</strong> service provided by Google LLC to protect our Website from spam, abuse, and automated bot activity. The reCAPTCHA service may collect information from you, including hardware and software information (such as device and application data), and send it to Google for analysis. Your use of reCAPTCHA is subject to Google's Privacy Policy (<a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>) and Terms of Use (<a href="https://policies.google.com/terms" target="_blank" rel="noopener noreferrer">https://policies.google.com/terms</a>).</p>

        <h3>8.2 Google Places</h3>
        <p>We use the <strong>Google Places</strong> service provided by Google LLC to retrieve and display information about business locations, addresses, and places on our Website. Information collected by Google Places is held in accordance with the Google Privacy Policy: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a></p>

        <h3>8.3 Mouseflow</h3>
        <p>As described in Section 4.1, Mouseflow provides behavioral analytics for our Website. See <a href="https://mouseflow.com/privacy/" target="_blank" rel="noopener noreferrer">https://mouseflow.com/privacy/</a> for details.</p>

        <h3>8.4 FreshDesk</h3>
        <p>We use <strong>Freshdesk</strong>, a customer support and helpdesk service provided by Freshworks Inc., to manage customer inquiries, support tickets, and communications. When you contact our support team, the information you provide (such as your name, email address, and the contents of your inquiry) may be processed and stored by Freshdesk. For more information, see the Freshworks Privacy Policy at: <a href="https://www.freshworks.com/privacy/" target="_blank" rel="noopener noreferrer">https://www.freshworks.com/privacy/</a></p>

        <h2>9. Email Communications</h2>
        <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials, service updates, troubleshooting tips, and other information that may be of interest to you. You may receive emails from us because:</p>
        <ul>
          <li>You opted in to receive emails from us (e.g., by subscribing to our newsletter);</li>
          <li>You made a purchase or created an account (transactional and service emails); or</li>
          <li>You contacted us with an inquiry (support-related emails).</li>
        </ul>
        <p><strong>Opting Out:</strong> You may opt out of receiving any, or all, marketing communications from us at any time by:</p>
        <ul>
          <li>Clicking the "unsubscribe" link included at the bottom of every marketing email we send;</li>
          <li>Contacting us using the contact details provided in Section 17 below.</li>
        </ul>
        <p>Please note that even if you opt out of marketing emails, we may still send you non-promotional communications, such as those about your account, purchases, or our ongoing business relationship.</p>

        <h2>10. How We Use Your Information</h2>
        <p>We use the collected data for various purposes, including to:</p>
        <ol>
          <li>Provide, operate, and maintain our Service;</li>
          <li>Improve, personalize, and expand our Service;</li>
          <li>Understand and analyze how you use our Service;</li>
          <li>Develop new products, services, features, and functionality;</li>
          <li>Process your transactions and manage your orders;</li>
          <li>Communicate with you, either directly or through one of our partners, including for customer service, support, updates, and marketing and promotional purposes;</li>
          <li>Send you emails, including newsletters you have subscribed to;</li>
          <li>Display and measure advertising, including personalized and remarketed advertising;</li>
          <li>Prevent fraud, spam, and abuse, and enforce our terms and policies;</li>
          <li>Comply with legal obligations, resolve disputes, and enforce agreements;</li>
          <li>Notify you about changes to our Service or this Privacy Policy.</li>
        </ol>

        <h2>11. Legal Bases for Processing (GDPR)</h2>
        <p>If you are from the European Economic Area (EEA), the United Kingdom, or Switzerland, our legal basis for collecting and using the Personal Data described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it. We may process your Personal Data because:</p>
        <ul>
          <li><strong>Consent:</strong> You have given us permission to do so (e.g., subscribing to our newsletter, accepting non-essential Cookies);</li>
          <li><strong>Performance of a Contract:</strong> The processing is necessary for the performance of a contract with you (e.g., processing a purchase);</li>
          <li><strong>Legitimate Interests:</strong> The processing is necessary for our legitimate interests, and those interests are not overridden by your rights (e.g., fraud prevention, improving our Service);</li>
          <li><strong>Legal Obligation:</strong> The processing is necessary for us to comply with the law (e.g., tax and accounting requirements).</li>
        </ul>

        <h3>11.1 Your Data Protection Rights Under GDPR</h3>
        <p>If you are a resident of the EEA, UK, or Switzerland, you have the following data protection rights:</p>
        <ul>
          <li><strong>Right of Access:</strong> The right to access, update, or delete the information we have on you. Wherever made possible, you can access, update, or request deletion of your Personal Data directly by contacting us.</li>
          <li><strong>Right of Rectification:</strong> The right to have your information corrected if it is inaccurate or incomplete.</li>
          <li><strong>Right to Object:</strong> The right to object to our processing of your Personal Data.</li>
          <li><strong>Right of Restriction:</strong> The right to request that we restrict the processing of your Personal Data.</li>
          <li><strong>Right to Data Portability:</strong> The right to be provided with a copy of your Personal Data in a structured, machine-readable, and commonly used format.</li>
          <li><strong>Right to Withdraw Consent:</strong> The right to withdraw your consent at any time where we relied on your consent to process your Personal Data. Withdrawal of consent does not affect the lawfulness of processing based on consent before its withdrawal.</li>
          <li><strong>Right to Lodge a Complaint:</strong> You have the right to complain to a Data Protection Authority (DPA) in the EEA member state of your habitual residence about our collection and use of your Personal Data.</li>
        </ul>
        <p>Please note that we may ask you to verify your identity before responding to such requests. We will respond to your request within one month, which may be extended by two further months where necessary, taking into account the complexity and number of requests.</p>

        <h3>11.2 International Data Transfers</h3>
        <p>Your information, including Personal Data, may be transferred to &mdash; and maintained on &mdash; computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.</p>
        <p>Where required, we implement appropriate safeguards for international transfers of Personal Data, such as Standard Contractual Clauses approved by the European Commission or reliance on adequacy decisions and certified frameworks (such as the EU-U.S. Data Privacy Framework, where our service providers are certified). Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>

        <h2>12. Children's Privacy (COPPA)</h2>
        <p>We collect information from children under the age of 13, and we do so in compliance with the Children's Online Privacy Protection Act (COPPA).</p>
        
        <h3>12.1 Parental Consent</h3>
        <p>Before collecting Personal Information from a child under 13, we obtain verifiable parental consent. We will:</p>
        <ul>
          <li>Provide direct notice to parents about our information practices before collecting Personal Information from their child;</li>
          <li>Obtain verifiable parental consent before collecting, using, or disclosing Personal Information from children under 13;</li>
          <li>Not condition a child's participation in an activity on the child disclosing more Personal Information than is reasonably necessary for that activity.</li>
        </ul>

        <h3>12.2 What We Collect from Children</h3>
        <p>The information we may collect from children under 13 is limited to what is reasonably necessary to provide the requested service and may include a first name, email address (or a parent's email address), and content voluntarily submitted through the Service.</p>

        <h3>12.3 Parental Rights</h3>
        <p>Parents and legal guardians have the right to:</p>
        <ul>
          <li><strong>Review</strong> the Personal Information we have collected from their child;</li>
          <li><strong>Request deletion</strong> of their child's Personal Information;</li>
          <li><strong>Refuse further collection or use</strong> of their child's Personal Information;</li>
          <li><strong>Revoke consent</strong> previously given, at any time.</li>
        </ul>
        <p>To exercise any of these rights, parents may contact us using the contact details in Section 17. We will take reasonable steps to verify the identity of anyone claiming to be a child's parent or guardian before providing access to the child's information.</p>

        <h3>12.4 No Behavioral Advertising to Children</h3>
        <p>We do not knowingly serve interest-based (behavioral) advertising to users we know to be under 13, and we do not knowingly permit third parties to collect Personal Information from children under 13 for behavioral advertising purposes.</p>
        <p>If you believe we have collected Personal Information from a child under 13 without appropriate parental consent, please contact us immediately so that we can investigate and take appropriate action, including deletion of the information.</p>

        <h2>13. Your California Privacy Rights (CCPA as Amended by CPRA)</h2>
        <p>This section applies to California residents and supplements the rest of this Privacy Policy. It is provided pursuant to the California Consumer Privacy Act of 2018 ("CCPA"), as amended by the California Privacy Rights Act of 2020 ("CPRA").</p>
        
        <h3>13.1 Categories of Personal Information We Collect</h3>
        <p>Within the last twelve (12) months, we have collected the following categories of Personal Information from consumers:</p>
        
        <div style={{ overflowX: 'auto', marginBottom: '1.5rem' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: '2px solid var(--border-color)', textAlign: 'left' }}>
                <th style={{ padding: '0.75rem' }}>Category</th>
                <th style={{ padding: '0.75rem' }}>Examples</th>
                <th style={{ padding: '0.75rem' }}>Collected</th>
              </tr>
            </thead>
            <tbody>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>A. Identifiers</td>
                <td style={{ padding: '0.75rem' }}>Name, email address, postal address, IP address, phone number</td>
                <td style={{ padding: '0.75rem' }}>Yes</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>B. Personal information categories listed in Cal. Civ. Code &sect; 1798.80(e)</td>
                <td style={{ padding: '0.75rem' }}>Name, address, phone number, payment information</td>
                <td style={{ padding: '0.75rem' }}>Yes</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>C. Protected classification characteristics</td>
                <td style={{ padding: '0.75rem' }}>Age (for COPPA compliance)</td>
                <td style={{ padding: '0.75rem' }}>Yes (limited)</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>D. Commercial information</td>
                <td style={{ padding: '0.75rem' }}>Products or services purchased, purchase history</td>
                <td style={{ padding: '0.75rem' }}>Yes</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>E. Biometric information</td>
                <td style={{ padding: '0.75rem' }}>Fingerprints, voiceprints</td>
                <td style={{ padding: '0.75rem' }}>No</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>F. Internet or similar network activity</td>
                <td style={{ padding: '0.75rem' }}>Browsing history, interactions with our Website and ads, session recordings</td>
                <td style={{ padding: '0.75rem' }}>Yes</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>G. Geolocation data</td>
                <td style={{ padding: '0.75rem' }}>Approximate location derived from IP address</td>
                <td style={{ padding: '0.75rem' }}>Yes</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>H. Sensory data</td>
                <td style={{ padding: '0.75rem' }}>Audio, visual information</td>
                <td style={{ padding: '0.75rem' }}>No</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>I. Professional or employment-related information</td>
                <td style={{ padding: '0.75rem' }}>Job title, employer</td>
                <td style={{ padding: '0.75rem' }}>No</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>J. Non-public education information</td>
                <td style={{ padding: '0.75rem' }}>Education records</td>
                <td style={{ padding: '0.75rem' }}>No</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>K. Inferences drawn from other personal information</td>
                <td style={{ padding: '0.75rem' }}>Preferences, characteristics, behavior</td>
                <td style={{ padding: '0.75rem' }}>Yes</td>
              </tr>
              <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                <td style={{ padding: '0.75rem' }}>L. Sensitive personal information</td>
                <td style={{ padding: '0.75rem' }}>Account log-in credentials; precise geolocation</td>
                <td style={{ padding: '0.75rem' }}>Limited (log-in credentials only, if you create an account)</td>
              </tr>
            </tbody>
          </table>
        </div>

        <h3>13.2 Sources of Personal Information</h3>
        <p>We obtain the categories of Personal Information listed above from: (a) directly from you (e.g., forms you complete, purchases you make); (b) indirectly from you (e.g., from observing your actions on our Website); (c) from social media platforms when you connect your account; and (d) from our Service Providers and advertising partners.</p>

        <h3>13.3 Sale or Sharing of Personal Information</h3>
        <p>Under the CCPA/CPRA, "sale" and "sharing" are defined broadly. The use of third-party advertising and analytics Cookies (such as those used for remarketing) may constitute "sharing" of Personal Information for cross-context behavioral advertising under the CPRA. The categories that may be "shared" for this purpose are Identifiers (Category A), Internet activity (Category F), and Inferences (Category K).</p>
        <p><strong>We do not knowingly sell or share the Personal Information of consumers under 16 years of age</strong> without affirmative authorization (opt-in consent from the consumer if aged 13&ndash;16, or from a parent or guardian if under 13).</p>

        <h3>13.4 Your Rights Under CCPA/CPRA</h3>
        <p>California residents have the following rights:</p>
        <ul>
          <li><strong>Right to Know:</strong> You may request that we disclose the categories and specific pieces of Personal Information we have collected about you, the categories of sources, the business purposes for collection, and the categories of third parties with whom we share it.</li>
          <li><strong>Right to Delete:</strong> You may request that we delete Personal Information we collected from you, subject to certain exceptions.</li>
          <li><strong>Right to Correct:</strong> You may request that we correct inaccurate Personal Information we maintain about you.</li>
          <li><strong>Right to Opt Out of Sale/Sharing:</strong> You may direct us not to sell or share your Personal Information. You can exercise this right by contacting us (Section 17) or by using any "Do Not Sell or Share My Personal Information" link made available on our Website.</li>
          <li><strong>Right to Limit Use of Sensitive Personal Information:</strong> You may request that we limit the use of your sensitive Personal Information to what is necessary to perform the services reasonably expected.</li>
          <li><strong>Right to Non-Discrimination:</strong> We will not discriminate against you for exercising any of your CCPA/CPRA rights. We will not deny you goods or services, charge you different prices, or provide a different level or quality of goods or services because you exercised your rights.</li>
        </ul>

        <h3>13.5 Exercising Your California Rights</h3>
        <p>To exercise your rights described above, please submit a verifiable consumer request to us using the contact details in Section 17. Only you, or a person registered with the California Secretary of State that you authorize to act on your behalf (an "authorized agent"), may make a verifiable consumer request related to your Personal Information. You may also make a verifiable consumer request on behalf of your minor child.</p>
        <p>We will confirm receipt of your request within ten (10) business days and respond within forty-five (45) calendar days. If we require more time (up to an additional 45 days), we will inform you of the reason and extension period in writing. You may make a request for disclosure up to twice within a 12-month period, free of charge.</p>

        <h3>13.6 Retention</h3>
        <p>We retain each category of Personal Information for as long as necessary to fulfill the purposes described in this Privacy Policy, comply with legal obligations, resolve disputes, and enforce our agreements. Criteria used to determine retention periods include the nature of the data, the purpose of processing, and applicable legal requirements.</p>

        <h2>14. California Online Privacy Protection Act (CalOPPA)</h2>
        <p>CalOPPA requires commercial websites and online services collecting Personal Information from California consumers to post a conspicuous privacy policy. In accordance with CalOPPA, we agree to the following:</p>
        <ul>
          <li>Users can visit our Website anonymously;</li>
          <li>A link to this Privacy Policy is included on our home page, or at a minimum, on the first significant page after entering our Website;</li>
          <li>Our Privacy Policy link includes the word "Privacy" and can be easily found on the pages specified above;</li>
          <li>Users will be notified of any privacy policy changes on this Privacy Policy page;</li>
          <li>Users can change their Personal Information by emailing us or by logging into their account (where applicable).</li>
        </ul>

        <h3>14.1 How We Respond to Do Not Track (DNT) Signals</h3>
        <p>Some web browsers incorporate a "Do Not Track" (DNT) feature that signals to websites that you do not want your online activity tracked. Because no uniform technology standard for recognizing and implementing DNT signals has been finalized, we do not currently respond to DNT browser signals. However, you may use the opt-out tools described in Sections 4, 5, and 7 to limit tracking, and California residents may exercise their opt-out rights described in Section 13.</p>

        <h2>15. Data Security</h2>
        <p>The security of your data is important to us. We implement commercially reasonable administrative, technical, and physical safeguards designed to protect your Personal Information from unauthorized access, use, alteration, and disclosure. These measures may include encryption in transit (SSL/TLS), access controls, and secure hosting infrastructure.</p>
        <p>However, please remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

        <h2>16. Data Retention</h2>
        <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable tax or accounting laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p>Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or improve the functionality of our Service, or when we are legally obligated to retain this data for longer periods.</p>

        <h2>17. Links to Other Websites</h2>
        <p>Our Service may contain links to other websites that are not operated by us. If you click a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>

        <h2>18. Changes to This Privacy Policy</h2>
        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date at the top of this Privacy Policy. For material changes, we may also provide additional notice, such as a prominent notice on our Website or an email notification (where we have your email address).</p>
        <p>Changes to this Privacy Policy are effective when they are posted on this page. Your continued use of the Service after any modification indicates your acceptance of the updated Privacy Policy.</p>

        <h2>19. Contact Us</h2>
        <p>If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, you can contact us:</p>
        <ul>
          <li><strong>By email:</strong> <a href="mailto:privacy@libertyprinterfix.com">privacy@libertyprinterfix.com</a></li>
          <li><strong>By visiting this page on our website:</strong> <Link href="/contact">https://libertyprinterfix.com/contact</Link></li>
          <li><strong>By post mail:</strong> Liberty Printer Fix, 123 Tech Support Way, Miami, Florida 33101, United States</li>
        </ul>
      </div>
    </div>
  );
}
